name: Selenium Tests Headless & Email Report

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'

    - name: Build Project
      run: mvn clean install -DskipTests

    - name: Run Selenium Tests (Headless)
      run: mvn test -Dheadless=true

    - name: Send Extent Report via Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Selenium Test Results
        to: yourrecipient@example.com
        from: ${{ secrets.MAIL_USERNAME }}
        body: | 
          Please find the attached Selenium Extent Report.
        attachments: target/SparkReport.html
